services:
  app:
    build: .
    env_file: .env
    volumes:
      - ./.env:/app/.env
    ports:
      - "${PORT:-8080}:8080"
    depends_on:
      - redis
  redis:
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
volumes:
  redis-data:
