services:
  redis:
    image: redis:7-alpine
    container_name: cody2zoho-redis-dev
    command: ["redis-server", "--appendonly", "yes", "--port", "6379"]
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  redis-data:
    driver: local
